### ISSUE TITLE
Avoid double negatives

### ISSUE THREAD

**Issue by l0b0** [cli-guidelines/cli-guidelines#112]
For example:

> You shouldn’t use a pager if stdin or stdout is not an interactive terminal.

Could be written as:

> Use a pager only if stdout is an interactive terminal.

(Also, why is stdin mentioned here? If I run `grep foo < bar`, stdin is not an interactive terminal, but I still would want a pager for `grep`'s stdout.)

**Comment by bfirsh** [comment]
Thanks for the suggestion! Pull requests welcome. :)
