### ISSUE TITLE
Incomplete Sentence

### ISSUE THREAD

**Issue by Sildoreth** [cli-guidelines/cli-guidelines#127]
Under Guidelines/Help, there is this incomplete sentence:
> Unless your program is very simple and does something obvious by default (e.g. ls), or your program reads input interactively (e.g. cat).

**Comment by aanand** [comment]
I think it's fair to say that this could be worded better. @TheRealJamesRussell good point about more richly interactive programs too - that's a better example than `cat` (which in my opinion does the _wrong_ thing when run with no arguments, but that's another conversation). I'll open a PR to reword.

**Comment by aanand** [comment]
https://github.com/cli-guidelines/cli-guidelines/pull/136
