### ISSUE TITLE
Don't recommend shell redirection of password file

### ISSUE THREAD

**Issue by willghatch** [cli-guidelines/cli-guidelines#32]
Using `--password $(< password.txt)` makes the contents of the `password.txt` file available to other programs and users in `ps` and related tools, just like typing the password literally on the command line does.  Don't list this as a possible way one should consider getting passwords -- if it's mentioned at all it should be discouraged.

You can quickly see this in action with this example:

```
echo "the-password" > /tmp/password.txt
cat - $(< /tmp/password.txt)
```

While leaving the cat command idle, in another terminal run `ps a | grep cat` to see the contents of the password file in your `ps` output.  This happens because the shell performs the `$()` expansion before ever running `cat`, and passes the result of the `$()` command verbatim to whichever version of `exec` the shell uses.

**Comment by aanand** [comment]
Thanks! I've added a note that it's insecure, and clarified our stance against it.
