### ISSUE TITLE
Clamp maximum font size

### ISSUE THREAD

**Issue by fafnirical** [cli-guidelines/cli-guidelines#36]
On a 3440x1440 monitor at full screen, the body text size is ~41.28px (`1vw * 1.2rem`, where `1vw = 34.40px`), which is pretty hard to read. The font size at >1600px could be clamped at 20px, rather than its current `1vw * 1.2rem`.

**Comment by josegonzalez** [comment]
The font here is massive on my 16" (3072 x 1920) Macbook. It makes it feel unreadable, and certainly goes against the idea that information density in CLIs is useful :)

**Comment by drtheuns** [comment]
Opening this on a vertical monitor gives an insane font-size for the title (without zoom):

![image](https://user-images.githubusercontent.com/10086452/101214610-9515a380-367c-11eb-9e48-6db3fe23f71f.png)

As you can see, the title caused a horizontal scrollbar to appear.

The default font size for body text is also quite big:

![image](https://user-images.githubusercontent.com/10086452/101214737-c42c1500-367c-11eb-90ea-a681737c1a2b.png)

I wouldn't have any problem with this normally, as I can just zoom out and get a reasonable font size, but the text does not scale down when zooming out, so the font always stays big.

**Comment by ihabunek** [comment]
Font size should not be defined relative to screen size, that makes it unscalable using zoom feature in the browser. It would be better to define font size in rem, perhaps a couple of sizes for various screen widths, and leave it at that. 

And I concur that the title font size is ridiculous. It's 256.6px on my screen.

**Comment by ThinkMake** [comment]
thanks for the feedback, as suggested I've clamped the upper font size for body text and limited the larger heading sizes to only apply on landscape viewports (where there is space for the text)

**Comment by ihabunek** [comment]
Much better. Thank you!
