### ISSUE TITLE
--help typography bug

### ISSUE THREAD

**Issue by simonw** [cli-guidelines/cli-guidelines#41]
It looks like `--help` got turned into an mdash or similar here (in the first line of text, not the code block example):

![1CC8205B-3D3D-4252-BBB4-02654F1E8E5C](https://user-images.githubusercontent.com/9599/101208755-7c2ed300-3627-11eb-99ef-0187aa7720bd.jpeg)

**Comment by tashian** [comment]
Fixed! Thanks @simonw. :D
