### ISSUE TITLE
What do you think about cisco ios/vyos cli design or powershell?

### ISSUE THREAD

**Issue by amreo** [cli-guidelines/cli-guidelines#59]
I think the guide need to examine other cli (non-unix based) designs like like vyos's (or cisco IOS) cli, msdos or powershell

https://docs.vyos.io/en/latest/cli.html

**Comment by tashian** [comment]
Thanks @amreo. While I agree that someone _should_  write guidelines documents for non-Unix-based OSs, this is out of scope for CLIG.
