### ISSUE TITLE
argparse for Python argument parsing?

### ISSUE THREAD

**Issue by brandonchinn178** [cli-guidelines/cli-guidelines#85]
I was surprised to not see argparse in the list of python cli libraries. Is there a particular reason why it is deemed not-great? Personally, the biggest thing it has going for it is that it's built in to Python, so you can use it for all your custom python scripts without needing to install third-party libraries.

**Comment by tashian** [comment]
Thanks @brandonchinn178. We should add argparse to the list.

**Comment by Rubix982** [comment]
Does [this PR](https://github.com/cli-guidelines/cli-guidelines/pull/88) solve this issue, @tashian, @brandonchinn178?

**Comment by tashian** [comment]
Yes @Rubix982, thanks!
